# Generated by Django 5.1.3 on 2024-12-03 18:41

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_driver_license_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True, validators=[users.validators.validate_telephone], verbose_name='телефон'),
        ),
    ]
