# Generated by Django 5.1.3 on 2024-12-03 18:51

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driver_license_number',
            field=models.IntegerField(validators=[users.validators.driver_license_number_validator], verbose_name='номер вод. удостоверения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='driver_license_series',
            field=models.IntegerField(validators=[users.validators.driver_license_series_validator], verbose_name='серия вод. удостоверения'),
        ),
    ]
