# Generated by Django 5.1.3 on 2024-12-04 17:59

import applications.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(unique=True, validators=[applications.validators.validate_time_between_8_and_18], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='application',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_applications', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
    ]
