# Generated by Django 5.1.3 on 2024-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_date_alter_application_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('completed', 'Выполненная')], default='new', max_length=50),
        ),
    ]
