# Generated by Django 5.1.3 on 2024-12-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
